### PR TITLE
Fix dependency issue with Flutter

### PR DESCRIPTION
**Pull request by erf**

### CODE REVIEW

**Comment by dmitryhryppa** [comment]
@just95 , hello!
Is it possible to revert this PR?

Because `petitparser 2.4.0` and `path 1.6.4` (which was set with this PR) too old and it conflicts with many libraries which uses the same dependencies..
But original `path: ^1.7.0` and `petitparser: ^3.0.2` looks like works fine, and works with latest Flutter as well.

**Comment by erf** [comment]
I can test to upgrade this on my fork and test against my `toml_localizations` package also, if everythings work, i will make a PR.

**Comment by erf** [comment]
I upgraded the packages and it seem to build and run fine on latest Flutter stable, so i made a PR #10

**Comment by dmitryhryppa** [comment]
Thank you!

**Comment by just95** [comment]
@dmitryhryppa thanks for pointing this out and thanks @erf again for the PR : )
[Version 0.6.1](https://pub.dev/packages/toml/versions/0.6.1) with updated dependencies is published now.

**Pull request merged**
